# Generated by Django 2.1.5 on 2019-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_opioids'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriberOpioids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorID', models.IntegerField(null=True)),
                ('DrugName', models.TextField(null=True)),
                ('Qty', models.IntegerField(null=True)),
            ],
        ),
    ]
