# Generated by Django 2.1.5 on 2019-04-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_prescriberopioids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opioid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.TextField(null=True)),
                ('IsOpioid', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriberOpioid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorID', models.IntegerField(null=True)),
                ('Fname', models.TextField(null=True)),
                ('Lname', models.TextField(null=True)),
                ('Gender', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('Credentials', models.TextField(null=True)),
                ('Specialty', models.TextField(null=True)),
                ('OpioidPrescriber', models.TextField(null=True)),
                ('TotalPrescriptions', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Opioids',
        ),
        migrations.DeleteModel(
            name='Prescriber',
        ),
        migrations.DeleteModel(
            name='PrescriberOpioids',
        ),
        migrations.AddField(
            model_name='prescriberopioid',
            name='DoctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Prescribers'),
        ),
        migrations.AddField(
            model_name='prescriberopioid',
            name='DrugName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Opioid'),
        ),
    ]
