# Generated by Django 2.1.5 on 2019-04-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190408_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorID', models.IntegerField(null=True)),
                ('Fname', models.TextField(null=True)),
                ('Lname', models.TextField(null=True)),
                ('Gender', models.TextField(null=True)),
                ('State', models.TextField(null=True)),
                ('Credentials', models.TextField(null=True)),
                ('Specialty', models.TextField(null=True)),
                ('OpioidPrescriber', models.TextField(null=True)),
                ('TotalPrescriptions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField(null=True)),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.TextField(null=True)),
                ('IsOpioid', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescriberopioid',
            name='DoctorID',
        ),
        migrations.RemoveField(
            model_name='prescriberopioid',
            name='DrugName',
        ),
        migrations.DeleteModel(
            name='Opioid',
        ),
        migrations.DeleteModel(
            name='PrescriberOpioid',
        ),
        migrations.DeleteModel(
            name='Prescribers',
        ),
        migrations.AddField(
            model_name='doctordrug',
            name='DrugName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Drug'),
        ),
    ]
