# Generated by Django 2.1.5 on 2019-04-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20190408_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='DoctorID',
        ),
        migrations.RemoveField(
            model_name='doctordrug',
            name='DoctorID',
        ),
    ]
