# Generated by Django 2.1.5 on 2019-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20190408_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdoctor',
            name='DoctorID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drugdoctor',
            name='DrugName',
            field=models.TextField(null=True),
        ),
    ]
