# Generated by Django 2.1.5 on 2019-04-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190408_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorID', models.IntegerField(null=True)),
                ('NumOpioids', models.TextField(null=True)),
                ('AtRisk', models.TextField(null=True)),
                ('PrescriberScore', models.TextField(null=True)),
            ],
        ),
    ]
